# Generated by Django 4.2.28 on 2026-02-14 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlowFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file_header_id', models.CharField(max_length=20)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=20)),
                ('meter_type', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_id', models.CharField(max_length=5)),
                ('reading_date', models.DateTimeField()),
                ('value', models.DecimalField(decimal_places=1, max_digits=10)),
                ('reading_type', models.CharField(blank=True, max_length=1)),
                ('is_estimated', models.BooleanField(default=False)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='meter_readings.meter')),
            ],
        ),
        migrations.CreateModel(
            name='MeterPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpan', models.CharField(max_length=13)),
                ('validation_status', models.CharField(max_length=1)),
                ('flow_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_points', to='meter_readings.flowfile')),
            ],
        ),
        migrations.AddField(
            model_name='meter',
            name='meter_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meters', to='meter_readings.meterpoint'),
        ),
    ]
